# Generated by Django 4.2.7 on 2025-11-30 05:23

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('peran', models.CharField(choices=[('Karyawan', 'Karyawan'), ('Owner', 'Owner')], default='Karyawan', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Akun',
                'verbose_name_plural': 'Akun',
                'db_table': 'tb_akun',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_layanan', models.CharField(max_length=100)),
                ('harga_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimasi_waktu', models.IntegerField(help_text='Estimasi waktu dalam hari')),
            ],
            options={
                'verbose_name': 'Layanan',
                'verbose_name_plural': 'Layanan',
                'db_table': 'tb_layanan',
            },
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelanggan', models.CharField(max_length=200)),
                ('nomor_handphone', models.CharField(max_length=15, unique=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('tanggal_registrasi', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pelanggan',
                'verbose_name_plural': 'Pelanggan',
                'db_table': 'tb_pelanggan',
            },
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_order', models.CharField(max_length=50, unique=True)),
                ('berat_cucian', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_biaya', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tanggal_masuk', models.DateTimeField(auto_now_add=True)),
                ('tanggal_estimasi_selesai', models.DateField()),
                ('catatan', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Diterima', 'Diterima'), ('Proses', 'Proses'), ('Selesai', 'Selesai'), ('Diambil', 'Diambil')], default='Diterima', max_length=20)),
                ('status_pembayaran', models.CharField(choices=[('Belum Lunas', 'Belum Lunas'), ('Lunas', 'Lunas')], default='Belum Lunas', max_length=20)),
                ('batas_penyimpanan', models.DateField(blank=True, null=True)),
                ('id_pegawai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaksi', to=settings.AUTH_USER_MODEL)),
                ('id_pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi', to='core.pelanggan')),
                ('jenis_layanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi', to='core.layanan')),
            ],
            options={
                'verbose_name': 'Transaksi',
                'verbose_name_plural': 'Transaksi',
                'db_table': 'tb_transaksi',
                'ordering': ['-tanggal_masuk'],
            },
        ),
        migrations.CreateModel(
            name='LogHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_sebelum', models.CharField(max_length=20)),
                ('status_sesudah', models.CharField(max_length=20)),
                ('waktu_perubahan', models.DateTimeField(auto_now_add=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('id_pegawai', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_history', to=settings.AUTH_USER_MODEL)),
                ('id_transaksi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_history', to='core.transaksi')),
            ],
            options={
                'verbose_name': 'Log History',
                'verbose_name_plural': 'Log History',
                'db_table': 'tb_log_history',
                'ordering': ['-waktu_perubahan'],
            },
        ),
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('nomor_hp', models.CharField(max_length=15)),
                ('akun', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karyawan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Karyawan',
                'verbose_name_plural': 'Karyawan',
                'db_table': 'tb_karyawan',
            },
        ),
    ]
