# Generated by Django 4.2.7 on 2025-11-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pengguna',
            name='nama_lengkap',
        ),
        migrations.RemoveField(
            model_name='pengguna',
            name='nomor_handphone',
        ),
        migrations.RemoveField(
            model_name='pengguna',
            name='tanggal_bergabung',
        ),
    ]
