# Generated by Django 4.2.7 on 2025-12-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaksi',
            index=models.Index(fields=['-tanggal_masuk'], name='tb_transaks_tanggal_638ea9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaksi',
            index=models.Index(fields=['status'], name='tb_transaks_status_f02b70_idx'),
        ),
        migrations.AddIndex(
            model_name='transaksi',
            index=models.Index(fields=['status_pembayaran'], name='tb_transaks_status__2c5962_idx'),
        ),
        migrations.AddIndex(
            model_name='transaksi',
            index=models.Index(fields=['tanggal_masuk', 'status'], name='tb_transaks_tanggal_181348_idx'),
        ),
    ]
