# Generated by Django 4.2.7 on 2025-11-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pengguna_nama_lengkap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='nama',
            field=models.CharField(default='', max_length=200),
        ),
    ]
