# Generated by Django 4.2.7 on 2025-11-28 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pengguna_nama'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE tb_pengguna DROP COLUMN IF EXISTS email;',
            reverse_sql='ALTER TABLE tb_pengguna ADD COLUMN email VARCHAR(254);',
        ),
    ]
