# Generated by Django 4.2.7 on 2025-11-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_email_column'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE tb_pengguna DROP COLUMN IF EXISTS first_name;',
            reverse_sql='ALTER TABLE tb_pengguna ADD COLUMN first_name VARCHAR(150);',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE tb_pengguna DROP COLUMN IF EXISTS last_name;',
            reverse_sql='ALTER TABLE tb_pengguna ADD COLUMN last_name VARCHAR(150);',
        ),
    ]
