# Generated by Django 4.2.7 on 2025-11-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_unused_fields'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE tb_pengguna ADD COLUMN nomor_handphone VARCHAR(15) DEFAULT '0' NOT NULL;",
            reverse_sql="ALTER TABLE tb_pengguna DROP COLUMN nomor_handphone;",
        ),
    ]
