# Generated by Django 4.2.7 on 2025-11-28 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_nomor_handphone'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE tb_transaksi SET status = 'Diambil' WHERE status = 'Sudah Diambil';",
            reverse_sql="UPDATE tb_transaksi SET status = 'Sudah Diambil' WHERE status = 'Diambil';",
        ),
        migrations.RunSQL(
            sql="UPDATE tb_log_history SET status_sebelum = 'Diambil' WHERE status_sebelum = 'Sudah Diambil';",
            reverse_sql="UPDATE tb_log_history SET status_sebelum = 'Sudah Diambil' WHERE status_sebelum = 'Diambil';",
        ),
        migrations.RunSQL(
            sql="UPDATE tb_log_history SET status_sesudah = 'Diambil' WHERE status_sesudah = 'Sudah Diambil';",
            reverse_sql="UPDATE tb_log_history SET status_sesudah = 'Sudah Diambil' WHERE status_sesudah = 'Diambil';",
        ),
    ]
